spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  # 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/kun-blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 3
      minIdle: 3
      maxActive: 15
      # 配置获取连接等待超时的时间
      maxWait: 5000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 90000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 1800000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      validationQuery: SELECT 1 FROM DUAL
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

# fastdfs连接配置
fdfs:
  groupName: kunkun
  soTimeout: 3000
  connectTimeout: 600
  # 缩略图生成参数
  thumbImage:
    width: 150
    height: 150
  # TrackerList参数,支持多个
  trackerList:
    - 168.168.28.10:9080
  fileServerUrl: http://168.168.28.10:8080/

# okhttp相关配置
ok:
  http:
    # 连接超时时间(秒)
    connect-timeout: 120
    # 读取超时时间(秒)
    read-timeout: 300
    # 写入超时时间(秒)
    write-timeout: 300