spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  security:
    user:
      name: root
      password: root
  redis:
    host: www.kun.com
    port: 6379
    password: admin123
  data:
    mongodb:
#      uri: mongodb://www.kun.com:27017/kun-cloud
      username: admin
      password: ${KUN_BLOG_MONGO_PASSWORD}
      host: www.kun.com
      port: 27017
      database: kun-cloud
      auto-index-creation: true
  # 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://www.kun.com:13306/kun-cloud?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      username: root
      password: qazWSX123
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 3
      minIdle: 3
      maxActive: 15
      # 配置获取连接等待超时的时间
      maxWait: 5000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 90000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 1800000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      validationQuery: SELECT 1 FROM DUAL
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

#用户初始化配置
user-init:
  # 默认头像
  head-portrait: aaa

# 手机短信配置
sms-config:
  # 是否开启测试环境
  test: true

# fastdfs连接配置
fdfs:
  groupName: group1
  soTimeout: 3000
  connectTimeout: 600
  # 缩略图生成参数
  thumbImage:
    width: 110
    height: 110
  # TrackerList参数,支持多个
  trackerList:
    - www.kun.com:22122
  fileServerUrl: http://www.kun.com:8888/

# okhttp相关配置
ok:
  http:
    # 连接超时时间(秒)
    connect-timeout: 120
    # 读取超时时间(秒)
    read-timeout: 300
    # 写入超时时间(秒)
    write-timeout: 300

rsa:
  private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKsz7P8PAPjN/QLOXz9+DsH6Z9nz34sjM2gUGQtVjNIX40y0ii+i+Vl3fcuCOmLvcSpAztrlJCFNvN9UX9VDK9XCOgS/fNV9bWzkqpXw0j7V9C1nwR/+8UM4oTPkJjHMmCC9chAW+lsk++6lZbFXzg7mh6d5NDMjdqqU4iSegcPNAgMBAAECgYB9SUqufPRhH52AaDYb6Mwz+GP3hBibYe9EwzBwsvKS7RhSEezuX33Kkz9jprHDpSZTnYnDdtyx4onNhZl8H+P7HIEemz3xKm5LFuXxldNtRxCti0gYm0xGHcQhpaEsmnv7Hjx5dZjTr39sq5FGuQHn2O3Ue1M7mGT/ne+r9KcZAQJBAPNDOsn1VcEBhN9/Ckgw3nsVZUeaXy9ObR39TVZQ06oMXCXjjJtnc0CB0eKk54vl45xY5J0cK9EcOCrRHiuDv7UCQQC0KsicrzBD4D2RWyftyAFfMa9WT3hpoxXDIZ6BhSk1E1xCMnL9E9wa3PIgwG82fQZLZAZSuOTMhXKylCdZe5K5AkEAkhY0ruYLep3r6sADL7lRUn9V1DtLoEAr3U+p6wUdJ8jGaeaOISFuIDYWElLPzr7fApyLpiIt2iVlQalVwfIb5QJAQp8Xc6jsZg0Ddz6H80tkBnlu5rGYSye9IlzKKga9iBzSnr/c+WxglaZh+m5uMW3l5/bix7ALGv21vgc+zb3+MQJBAI7+qj+YAhNa6GvV/qTi7Xbmi397DXQEoPtkU/exb3J4GQm17YTEFPT5Wp/FsRdRml9MEtM6ba1c9016vYDfDOw=

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  secret: k09BQnaF
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认7天，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 604800000
  # 在线用户key
  online-key: online-token_
  # 验证码
  code-key: code-key_