server:
  port: 9200
spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: 112.74.169.107
    port: 5672
    username: admin
    password: admin
    # 开启消息确认
    #确认消息已发送到交换机(Exchange)
#    publisher-confirm-type: correlated
#    #确认消息已发送到队列(Queue
#    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

rocketmq:
  name-server: 116.205.172.254:9876
  producer:
    group: my-producer-group
